using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace WebApplication1.Models {
    public class PaymentModel {
        public int Id { get; set; } // Primary key, auto-generated by EF

        [Required]
        [StringLength(255)]
        [Display(Name = "Name-Surname")]
        public string NameSurname { get; set; }

        [Required]
        [StringLength(16)]
        [MinLength(16)]
        [MaxLength(16)]
        [Display(Name = "Card Number")]
        public string CardNumber { get; set; }

        [Required]
        [StringLength(5)]
        [RegularExpression(@"^\d{2}/\d{2}$")]
        [Display(Name = "Expiration Date")]
        public string Expiry { get; set; }

        [Required]
        [StringLength(3)]
        [RegularExpression(@"^\d{3}$")]
        [Display(Name = "CVV")]
        public string CVV { get; set; }

        [Required]
        [StringLength(255)]
        [Display(Name = "Movie Name")]
        public string MovieName { get; set; }

        [Required]
        [Display(Name = "Total Price")]
        public double TotalPrice { get; set; }


    }
}
